apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestli
  template:
    metadata:
      labels:
        app: bestli
    spec:
      containers:
      - image: okteto.dev/bestli:latest
        name: bestli
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "fa7c2f79-ae32-43cc-8af1-310a2080dd1d"
        - name: Vless_Path
          value: "/baidu"
        - name: Vmess_UUID
          value: "fa7c2f79-ae32-43cc-8af1-310a2080dd1d"
        - name: Vmess_Path
          value: "/baidu"
        - name: Share_Path
          value: "/v2link"
